source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "7.0"

   pod 'MJRefresh', '~> 3.1.9'
pod 'SDWebImage'
pod 'XMPPFramework'
pod 'FMDB'
pod 'MBProgressHUD'
pod 'IQKeyboardManager'
pod 'MJExtension', '~> 3.0.11'

target :Flower do
# pod 'Kiwi'
end
