source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "8.0"

pod 'MJExtension', '~> 3.0.10'
pod 'SDWebImage', '~> 3.7.6'
pod 'MJRefresh', '~> 3.1.0'
   pod 'MBProgressHUD', '~> 0.9.2'

target :xiaorizi do
  # pod 'Kiwi'
end
