source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "7.0"

pod 'MJRefresh'
pod 'SDWebImage'
pod 'XMPPFramework'
pod 'FMDB'
pod 'MBProgressHUD'
pod 'IQKeyboardManager'

target :Flower do
# pod 'Kiwi'
end
